---
galaxy_info:
  role_name: awx_galaxy_ng_k8s
  author: AWX
  description: Deploy Galaxy NG beside AWX in k3s or Kubernetes.
  license: GPL-3.0-or-later
  min_ansible_version: "2.15"
dependencies: []
