# Generated by Django migrations

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0213_oci_credential_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, default='')),
                ('name', models.CharField(max_length=512)),
                ('icon_url', models.URLField(blank=True, default='', help_text='Optional URL for a display icon.', max_length=1024)),
                ('extra_vars_schema', models.JSONField(blank=True, default=None, help_text='JSON Schema describing the parameters presented to the user at deploy time. If null, no extra-var form is shown.', null=True)),
                ('organization', models.ForeignKey(
                    blank=True,
                    default=None,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='catalog_items',
                    to='main.organization',
                )),
                ('provision_workflow', models.ForeignKey(
                    blank=True,
                    default=None,
                    help_text='Workflow to run when a user deploys this item.',
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='catalog_items_as_provision',
                    to='main.workflowjobtemplate',
                )),
                ('deprovision_workflow', models.ForeignKey(
                    blank=True,
                    default=None,
                    help_text='Workflow to run when a user decommissions a deployment.',
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='catalog_items_as_deprovision',
                    to='main.workflowjobtemplate',
                )),
                ('admin_role', models.OneToOneField(
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='catalogitem_admin_role',
                    to='main.role',
                )),
                ('use_role', models.OneToOneField(
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='catalogitem_use_role',
                    to='main.role',
                )),
                ('read_role', models.OneToOneField(
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='catalogitem_read_role',
                    to='main.role',
                )),
                ('created_by', models.ForeignKey(
                    default=None,
                    editable=False,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='catalogitem_created+',
                    to=settings.AUTH_USER_MODEL,
                )),
                ('modified_by', models.ForeignKey(
                    default=None,
                    editable=False,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='catalogitem_modified+',
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
            options={
                'ordering': ('name',),
                'app_label': 'main',
            },
        ),
        migrations.CreateModel(
            name='CatalogDeployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, default='')),
                ('name', models.CharField(max_length=512)),
                ('status', models.CharField(
                    choices=[
                        ('pending', 'Pending'),
                        ('provisioning', 'Provisioning'),
                        ('active', 'Active'),
                        ('deprovisioning', 'Deprovisioning'),
                        ('failed', 'Failed'),
                        ('destroyed', 'Destroyed'),
                    ],
                    default='pending',
                    max_length=32,
                )),
                ('extra_vars', models.JSONField(blank=True, default=None, help_text='Variable values supplied by the user at deploy time.', null=True)),
                ('catalog_item', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='deployments',
                    to='main.catalogitem',
                )),
                ('owner', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='catalog_deployments',
                    to=settings.AUTH_USER_MODEL,
                )),
                ('provision_job', models.ForeignKey(
                    blank=True,
                    default=None,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='catalog_deployments_as_provision',
                    to='main.workflowjob',
                )),
                ('deprovision_job', models.ForeignKey(
                    blank=True,
                    default=None,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='catalog_deployments_as_deprovision',
                    to='main.workflowjob',
                )),
                ('deployed_hosts', models.ManyToManyField(
                    blank=True,
                    related_name='catalog_deployments',
                    to='main.host',
                )),
                ('created_by', models.ForeignKey(
                    default=None,
                    editable=False,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='catalogdeployment_created+',
                    to=settings.AUTH_USER_MODEL,
                )),
                ('modified_by', models.ForeignKey(
                    default=None,
                    editable=False,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='catalogdeployment_modified+',
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
            options={
                'ordering': ('-created',),
                'app_label': 'main',
            },
        ),
    ]
