# Generated by Django 5.2.8 on 2026-05-26 03:11

import awx.main.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0215_terraform_role_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogdeployment',
            options={'default_permissions': ('change', 'delete', 'view'), 'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='catalogitem',
            options={'default_permissions': ('change', 'delete', 'view'), 'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='activitystream',
            name='terraform_job',
            field=models.ManyToManyField(blank=True, to='main.terraformjob'),
        ),
        migrations.AddField(
            model_name='activitystream',
            name='terraform_job_template',
            field=models.ManyToManyField(blank=True, to='main.terraformjobtemplate'),
        ),
        migrations.AlterField(
            model_name='catalogdeployment',
            name='created',
            field=models.DateTimeField(default=None, editable=False),
        ),
        migrations.AlterField(
            model_name='catalogdeployment',
            name='created_by',
            field=models.ForeignKey(
                default=None,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='%s(class)s_created+',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='catalogdeployment',
            name='modified',
            field=models.DateTimeField(default=None, editable=False),
        ),
        migrations.AlterField(
            model_name='catalogdeployment',
            name='modified_by',
            field=models.ForeignKey(
                default=None,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='%s(class)s_modified+',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='admin_role',
            field=awx.main.fields.ImplicitRoleField(
                editable=False,
                null='True',
                on_delete=django.db.models.deletion.SET_NULL,
                parent_role=['organization.admin_role'],
                related_name='+',
                to='main.role',
            ),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='created',
            field=models.DateTimeField(default=None, editable=False),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='created_by',
            field=models.ForeignKey(
                default=None,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='%s(class)s_created+',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='modified',
            field=models.DateTimeField(default=None, editable=False),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='modified_by',
            field=models.ForeignKey(
                default=None,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='%s(class)s_modified+',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='read_role',
            field=awx.main.fields.ImplicitRoleField(
                editable=False,
                null='True',
                on_delete=django.db.models.deletion.SET_NULL,
                parent_role=['admin_role', 'use_role', 'organization.auditor_role'],
                related_name='+',
                to='main.role',
            ),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='use_role',
            field=awx.main.fields.ImplicitRoleField(
                editable=False,
                null='True',
                on_delete=django.db.models.deletion.SET_NULL,
                parent_role=['admin_role', 'organization.member_role'],
                related_name='+',
                to='main.role',
            ),
        ),
        migrations.AlterField(
            model_name='terraformjob',
            name='scm_revision',
            field=models.CharField(
                blank=True, default='', editable=False, help_text='The SCM revision of the project that was checked out for this job.', max_length=1024
            ),
        ),
        migrations.AlterField(
            model_name='terraformjobtemplate',
            name='ask_inventory_on_launch',
            field=awx.main.fields.AskForField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='terraformjobtemplate',
            name='ask_labels_on_launch',
            field=awx.main.fields.AskForField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='terraformjobtemplate',
            name='ask_limit_on_launch',
            field=awx.main.fields.AskForField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='terraformjobtemplate',
            name='ask_scm_branch_on_launch',
            field=awx.main.fields.AskForField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='terraformjobtemplate',
            name='ask_skip_tags_on_launch',
            field=awx.main.fields.AskForField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='terraformjobtemplate',
            name='ask_tags_on_launch',
            field=awx.main.fields.AskForField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='terraformjobtemplate',
            name='ask_terraform_operation_on_launch',
            field=awx.main.fields.AskForField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='terraformjobtemplate',
            name='ask_variables_on_launch',
            field=awx.main.fields.AskForField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='terraformjobtemplate',
            name='extra_vars',
            field=models.TextField(blank=True, default='', help_text='Variables to pass to Terraform as a tfvars file. Accepts JSON or YAML key/value pairs.'),
        ),
        migrations.AlterField(
            model_name='terraformjobtemplate',
            name='target_group',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Inventory group to add provisioned hosts to. The group is created automatically if it does not exist.',
                max_length=512,
            ),
        ),
        migrations.AlterField(
            model_name='terraformjobtemplate',
            name='target_inventory',
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text='If set, after a successful apply AWX will read Terraform output variables and create Host records in this inventory for each value named "host_ip_*".',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='terraform_job_templates',
                to='main.inventory',
            ),
        ),
        migrations.AlterField(
            model_name='terraformjobtemplate',
            name='terraform_dir',
            field=models.CharField(
                blank=True,
                default='.',
                help_text='Path within the project to the directory containing the Terraform root module. Use "." for the repository root (default).',
                max_length=1024,
            ),
        ),
    ]
