# Generated by Django 5.2.8 on 2026-05-26 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0216_activity_stream_terraform_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='terraformjob',
            name='allow_simultaneous',
            field=models.BooleanField(default=False, help_text='Allow simultaneous runs of this job.'),
        ),
    ]
