# Generated by Django 5.2.8 on 2026-05-26 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0217_terraform_job_allow_simultaneous'),
    ]

    operations = [
        migrations.AddField(
            model_name='terraformjob',
            name='timeout',
            field=models.IntegerField(blank=True, default=0, help_text='The amount of time (in seconds) to run before the task is canceled.'),
        ),
    ]
