# Generated by Django 5.2.8 on 2026-05-26 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0219_terraform_job_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnpartitionedTerraformJobEvent',
            fields=[],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.terraformjobevent',),
        ),
        migrations.RenameIndex(
            model_name='terraformjobevent',
            new_name='main_terraf_terrafo_c8bb0f_idx',
            old_name='main_terraformjobevent_tfj_created_uuid_idx',
        ),
        migrations.RenameIndex(
            model_name='terraformjobevent',
            new_name='main_terraf_terrafo_c54ed5_idx',
            old_name='main_terraformjobevent_tfj_created_counter_idx',
        ),
        migrations.AddField(
            model_name='catalogdeployment',
            name='terraform_provision_job',
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='catalog_deployments_as_terraform_provision',
                to='main.terraformjob',
            ),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='terraform_job_template',
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text='Terraform template to run when a user deploys this item (alternative to provision_workflow).',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='catalog_items',
                to='main.terraformjobtemplate',
            ),
        ),
    ]
