# Generated by Django 4.2.20 on 2026-05-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0224_terraformjob_artifacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='override_workflow_limit',
            field=models.BooleanField(
                default=True,
                help_text='When enabled, deployment launches include terraform_override_limit=true.',
            ),
        ),
    ]
