# Generated by Django 4.2.20 on 2026-05-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0225_catalog_item_override_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='icon_data',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Optional base64-encoded image (data URL) used for catalog item icon upload.',
            ),
        ),
        migrations.AddField(
            model_name='catalogdeployment',
            name='last_deprovision_vars',
            field=models.JSONField(
                blank=True,
                default=None,
                help_text='Resolved variables passed to the most recent deprovision workflow launch.',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='catalogdeployment',
            name='last_failed_workflow_job',
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=models.SET_NULL,
                related_name='catalog_deployments_as_last_failed',
                to='main.workflowjob',
            ),
        ),
        migrations.AddField(
            model_name='catalogdeployment',
            name='provisioning_history',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Chronological record of provision/deprovision/retry job attempts for this deployment.',
            ),
        ),
    ]
