# Generated by Django 4.2.20 on 2026-05-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0226_catalog_item_upload_and_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='name_template',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Optional deployment name template. Use {user_org_name} for the normalized organization name and append +1 to enable sequential numbering.',
                max_length=1024,
            ),
        ),
    ]
