# Generated by Django 4.2.20 on 2026-05-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0227_catalog_item_name_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='dynamic_name_field',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Optional deploy variable name to auto-populate as a dynamic field (for example, vmnam).',
                max_length=256,
            ),
        ),
    ]
