# Generated by Django 4.2.20 on 2026-05-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0228_catalog_item_dynamic_name_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='dynamic_field_templates',
            field=models.JSONField(
                blank=True,
                default=None,
                help_text='Optional per-field dynamic values keyed by deploy variable name. These values are independent from name_template.',
                null=True,
            ),
        ),
    ]
