# Generated by Django 4.2.20 on 2026-05-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0229_catalog_item_dynamic_field_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='deploy_disabled_fields',
            field=models.JSONField(
                blank=True,
                default=None,
                help_text='Optional list of deploy field names that should be read-only in the deploy form for this catalog item.',
                null=True,
            ),
        ),
    ]
