# Generated by Django 5.2.8 on 2026-05-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0233_cloud_provider_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitystream',
            name='cloud_provider_connection',
            field=models.ManyToManyField(blank=True, to='main.cloudproviderconnection'),
        ),
        migrations.AddField(
            model_name='activitystream',
            name='cloud_provider_state',
            field=models.ManyToManyField(blank=True, to='main.cloudproviderstate'),
        ),
        migrations.AlterField(
            model_name='cloudproviderstate',
            name='admin_settings',
            field=models.JSONField(blank=True, default=None, help_text='Admin allow-list settings for this provider (e.g. allowed size slugs).', null=True),
        ),
        migrations.AlterField(
            model_name='cloudproviderstate',
            name='provider_data',
            field=models.JSONField(blank=True, default=None, help_text='Raw pulled resource data (images, sizes, regions, VPCs, etc.).', null=True),
        ),
        migrations.AlterField(
            model_name='cloudproviderstate',
            name='provider_settings',
            field=models.JSONField(blank=True, default=None, help_text='General provider settings (allow template pull, allowed networks, etc.).', null=True),
        ),
    ]
