# Generated by Django 5.2.8 on 2026-05-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0234_activity_stream_cloud_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='cloud_backends',
            field=models.JSONField(
                blank=True,
                default=None,
                help_text='Mapping of cloud provider id to TerraformJobTemplate pk for multi-cloud deployments. e.g. {"digitalocean": 5, "azure": 12}. When set, the deploy wizard offers a provider selector.',
                null=True,
            ),
        ),
    ]
