# Generated by Django 5.2.8 on 2026-05-29 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0238_catalogitem_provider_field_configs'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='provider_deprovision_workflows',
            field=models.JSONField(
                blank=True,
                default=None,
                help_text='Mapping of cloud provider slug to WorkflowJobTemplate pk used to deprovision resources for that provider. e.g. {"digitalocean": 26, "proxmox": 22}.',
                null=True,
            ),
        ),
    ]
