# Generated by Django 5.2.8 on 2026-05-31 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0245_cloudproviderconnection_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogdeployment',
            name='expires_at',
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text='When set, the deployment will be considered expired after this UTC datetime. If auto_deprovision is also True the deprovision workflow will be triggered automatically.',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='catalogdeployment',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending'),
                    ('provisioning', 'Provisioning'),
                    ('configuring', 'Configuring'),
                    ('validating', 'Validating'),
                    ('active', 'Active'),
                    ('deprovisioning', 'Deprovisioning'),
                    ('failed', 'Failed'),
                    ('destroyed', 'Destroyed'),
                ],
                default='pending',
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='require_lease',
            field=models.BooleanField(
                default=False,
                help_text='When enabled, deployers must supply a TTL before the deployment is created. Deployments will not be created without an expiry time.',
            ),
        ),
    ]
