# Generated by Django 5.2.8 on 2026-05-31

from django.db import migrations, models

from awx.main.migrations._dab_rbac import setup_managed_role_definitions


def sync_catalogitem_dab_permissions(apps, schema_editor):
    """
    Create DABContentType, DABPermission, and RoleDefinition entries for
    CatalogItem after adding its object-level use permission.
    """
    from ansible_base.rbac.management import sync_dab_permissions

    sync_dab_permissions(apps=apps)
    setup_managed_role_definitions(apps, schema_editor)


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0246_catalog_ttl_field_metadata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogitem',
            options={
                'default_permissions': ('change', 'delete', 'view'),
                'ordering': ('name',),
                'permissions': [('use_catalogitem', 'Can deploy this catalog item')],
            },
        ),
        migrations.AddField(
            model_name='activitystream',
            name='catalog_item',
            field=models.ManyToManyField(blank=True, to='main.catalogitem'),
        ),
        migrations.RunPython(sync_catalogitem_dab_permissions, migrations.RunPython.noop),
    ]
