# Generated by Django 5.2.8 on 2026-05-31 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0247_catalogitem_activity_stream_rbac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogdeployment',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending'),
                    ('provisioning', 'Provisioning'),
                    ('configuring', 'Configuring'),
                    ('validating', 'Validating'),
                    ('active', 'Active'),
                    ('expired', 'Expired'),
                    ('deprovisioning', 'Deprovisioning'),
                    ('failed', 'Failed'),
                    ('destroyed', 'Destroyed'),
                ],
                default='pending',
                max_length=32,
            ),
        ),
    ]
