# Generated by AWX on 2026-06-04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0251_profile_ui_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='default_machine_credential',
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text='Machine credential to use for jobs launched with this inventory when no machine credential is supplied by the job template or launch prompt.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='default_for_inventories',
                to='main.credential',
            ),
        ),
        migrations.AddField(
            model_name='inventory',
            name='force_inventory_machine_credential',
            field=models.BooleanField(
                default=False,
                help_text='If enabled, jobs launched with this inventory use the inventory machine credential even when the job template has one.',
            ),
        ),
    ]
