# Generated by Codex on 2026-07-02

import awx.main.fields
import awx.main.models.notifications
import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone

from awx.main.migrations._implicit_roles import create_missing_implicit_roles


def migrate_quay_templates_to_unified_job_templates(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Project = apps.get_model('main', 'Project')
    QuayImageBuild = apps.get_model('main', 'QuayImageBuild')
    QuayImageBuildTemplate = apps.get_model('main', 'QuayImageBuildTemplate')
    UnifiedJobTemplate = apps.get_model('main', 'UnifiedJobTemplate')

    content_type, _created = ContentType.objects.get_or_create(app_label='main', model='quayimagebuildtemplate')
    now = timezone.now()
    existing_child_ids = list(QuayImageBuildTemplate.objects.values_list('id', flat=True))
    UnifiedJobTemplate.objects.filter(polymorphic_ctype_id=content_type.id).exclude(id__in=existing_child_ids).delete()

    for template in list(QuayImageBuildTemplate.objects.order_by('id')):
        project = Project.objects.filter(pk=template.project_id).first() if template.project_id else None
        parent_values = {
            'polymorphic_ctype_id': content_type.id,
            'created': template.created or now,
            'modified': template.modified or now,
            'description': template.description or '',
            'created_by_id': template.created_by_id,
            'modified_by_id': template.modified_by_id,
            'name': template.name,
            'organization_id': project.organization_id if project else None,
            'status': 'never updated',
            'org_unique': True,
        }

        if UnifiedJobTemplate.objects.filter(pk=template.id).exists():
            parent = UnifiedJobTemplate.objects.create(**parent_values)
            old_id = template.id
            new_id = parent.id
            build_ids = list(QuayImageBuild.objects.filter(template_id=old_id).values_list('id', flat=True))
            QuayImageBuild.objects.filter(id__in=build_ids).update(template_id=None)
            QuayImageBuildTemplate.objects.filter(pk=old_id).update(id=new_id)
            QuayImageBuild.objects.filter(id__in=build_ids).update(template_id=new_id)
        else:
            UnifiedJobTemplate.objects.create(id=template.id, **parent_values)


def noop_reverse(apps, schema_editor):
    pass


def create_quay_template_implicit_roles(apps, schema_editor):
    create_missing_implicit_roles(apps, 'QuayImageBuildTemplate')


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('main', '0261_quay_image_build_template'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quayimagebuildtemplate',
            options={
                'default_permissions': ('change', 'delete', 'view'),
                'ordering': ('name', 'id'),
                'permissions': [('execute_quayimagebuildtemplate', 'Can run this Project Quay image build template')],
            },
        ),
        migrations.RunPython(migrate_quay_templates_to_unified_job_templates, noop_reverse),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RemoveField(
                    model_name='quayimagebuildtemplate',
                    name='created',
                ),
                migrations.RemoveField(
                    model_name='quayimagebuildtemplate',
                    name='created_by',
                ),
                migrations.RemoveField(
                    model_name='quayimagebuildtemplate',
                    name='description',
                ),
                migrations.RemoveField(
                    model_name='quayimagebuildtemplate',
                    name='modified',
                ),
                migrations.RemoveField(
                    model_name='quayimagebuildtemplate',
                    name='modified_by',
                ),
                migrations.RemoveField(
                    model_name='quayimagebuildtemplate',
                    name='name',
                ),
                migrations.AddField(
                    model_name='quayimagebuildtemplate',
                    name='admin_role',
                    field=awx.main.fields.ImplicitRoleField(
                        editable=False,
                        null='True',
                        on_delete=django.db.models.deletion.SET_NULL,
                        parent_role=['organization.execution_environment_admin_role', 'organization.job_template_admin_role'],
                        related_name='+',
                        to='main.role',
                    ),
                ),
                migrations.AddField(
                    model_name='quayimagebuildtemplate',
                    name='execute_role',
                    field=awx.main.fields.ImplicitRoleField(
                        editable=False,
                        null='True',
                        on_delete=django.db.models.deletion.SET_NULL,
                        parent_role=['admin_role', 'organization.execute_role'],
                        related_name='+',
                        to='main.role',
                    ),
                ),
                migrations.AddField(
                    model_name='quayimagebuildtemplate',
                    name='read_role',
                    field=awx.main.fields.ImplicitRoleField(
                        editable=False,
                        null='True',
                        on_delete=django.db.models.deletion.SET_NULL,
                        parent_role=['admin_role', 'execute_role', 'organization.auditor_role'],
                        related_name='+',
                        to='main.role',
                    ),
                ),
                migrations.CreateModel(
                    name='QuayImageBuildJob',
                    fields=[
                        (
                            'unifiedjob_ptr',
                            models.OneToOneField(
                                auto_created=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                parent_link=True,
                                primary_key=True,
                                serialize=False,
                                to='main.unifiedjob',
                            ),
                        ),
                        ('namespace', models.CharField(max_length=255)),
                        ('repository', models.CharField(max_length=255)),
                        ('tag', models.CharField(default='latest', max_length=128)),
                        ('image', models.CharField(blank=True, default='', max_length=1024)),
                        ('registry', models.CharField(blank=True, default='', max_length=512)),
                        ('runtime', models.CharField(default='podman', max_length=16)),
                        ('definition_file', models.CharField(default='execution-environment.yml', max_length=1024)),
                        ('context_path', models.CharField(default='.', max_length=1024)),
                        ('scm_revision', models.CharField(blank=True, default='', editable=False, max_length=1024)),
                        ('progress', models.PositiveSmallIntegerField(default=0)),
                        ('command_summary', models.JSONField(blank=True, default=list)),
                        (
                            'project',
                            models.ForeignKey(
                                blank=True,
                                default=None,
                                help_text='AWX Project used as the execution environment build source.',
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name='quay_image_build_jobs',
                                to='main.project',
                            ),
                        ),
                        (
                            'quay_image_build_template',
                            models.ForeignKey(
                                blank=True,
                                default=None,
                                help_text='Project Quay image build template that produced this job.',
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name='jobs',
                                to='main.quayimagebuildtemplate',
                            ),
                        ),
                    ],
                    options={
                        'ordering': ('id',),
                    },
                    bases=('main.unifiedjob', awx.main.models.notifications.JobNotificationMixin, models.Model),
                ),
                migrations.AddField(
                    model_name='quayimagebuild',
                    name='unified_job',
                    field=models.OneToOneField(
                        blank=True,
                        default=None,
                        help_text='Native AWX unified job that owns this Project Quay image build run.',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='quay_image_build',
                        to='main.quayimagebuildjob',
                    ),
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='quayimagebuildtemplate',
                    name='created',
                ),
                migrations.RemoveField(
                    model_name='quayimagebuildtemplate',
                    name='created_by',
                ),
                migrations.RemoveField(
                    model_name='quayimagebuildtemplate',
                    name='description',
                ),
                migrations.RemoveField(
                    model_name='quayimagebuildtemplate',
                    name='id',
                ),
                migrations.RemoveField(
                    model_name='quayimagebuildtemplate',
                    name='modified',
                ),
                migrations.RemoveField(
                    model_name='quayimagebuildtemplate',
                    name='modified_by',
                ),
                migrations.RemoveField(
                    model_name='quayimagebuildtemplate',
                    name='name',
                ),
                migrations.AddField(
                    model_name='quayimagebuildtemplate',
                    name='admin_role',
                    field=awx.main.fields.ImplicitRoleField(
                        editable=False,
                        null='True',
                        on_delete=django.db.models.deletion.SET_NULL,
                        parent_role=['organization.execution_environment_admin_role', 'organization.job_template_admin_role'],
                        related_name='+',
                        to='main.role',
                    ),
                ),
                migrations.AddField(
                    model_name='quayimagebuildtemplate',
                    name='execute_role',
                    field=awx.main.fields.ImplicitRoleField(
                        editable=False,
                        null='True',
                        on_delete=django.db.models.deletion.SET_NULL,
                        parent_role=['admin_role', 'organization.execute_role'],
                        related_name='+',
                        to='main.role',
                    ),
                ),
                migrations.AddField(
                    model_name='quayimagebuildtemplate',
                    name='read_role',
                    field=awx.main.fields.ImplicitRoleField(
                        editable=False,
                        null='True',
                        on_delete=django.db.models.deletion.SET_NULL,
                        parent_role=['admin_role', 'execute_role', 'organization.auditor_role'],
                        related_name='+',
                        to='main.role',
                    ),
                ),
                migrations.AddField(
                    model_name='quayimagebuildtemplate',
                    name='unifiedjobtemplate_ptr',
                    field=models.OneToOneField(
                        auto_created=True,
                        db_column='id',
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='main.unifiedjobtemplate',
                    ),
                ),
                migrations.CreateModel(
                    name='QuayImageBuildJob',
                    fields=[
                        (
                            'unifiedjob_ptr',
                            models.OneToOneField(
                                auto_created=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                parent_link=True,
                                primary_key=True,
                                serialize=False,
                                to='main.unifiedjob',
                            ),
                        ),
                        ('namespace', models.CharField(max_length=255)),
                        ('repository', models.CharField(max_length=255)),
                        ('tag', models.CharField(default='latest', max_length=128)),
                        ('image', models.CharField(blank=True, default='', max_length=1024)),
                        ('registry', models.CharField(blank=True, default='', max_length=512)),
                        ('runtime', models.CharField(default='podman', max_length=16)),
                        ('definition_file', models.CharField(default='execution-environment.yml', max_length=1024)),
                        ('context_path', models.CharField(default='.', max_length=1024)),
                        ('scm_revision', models.CharField(blank=True, default='', editable=False, max_length=1024)),
                        ('progress', models.PositiveSmallIntegerField(default=0)),
                        ('command_summary', models.JSONField(blank=True, default=list)),
                        (
                            'project',
                            models.ForeignKey(
                                blank=True,
                                default=None,
                                help_text='AWX Project used as the execution environment build source.',
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name='quay_image_build_jobs',
                                to='main.project',
                            ),
                        ),
                        (
                            'quay_image_build_template',
                            models.ForeignKey(
                                blank=True,
                                default=None,
                                help_text='Project Quay image build template that produced this job.',
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name='jobs',
                                to='main.quayimagebuildtemplate',
                            ),
                        ),
                    ],
                    options={
                        'ordering': ('id',),
                    },
                    bases=('main.unifiedjob', awx.main.models.notifications.JobNotificationMixin, models.Model),
                ),
                migrations.AddField(
                    model_name='quayimagebuild',
                    name='unified_job',
                    field=models.OneToOneField(
                        blank=True,
                        default=None,
                        help_text='Native AWX unified job that owns this Project Quay image build run.',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='quay_image_build',
                        to='main.quayimagebuildjob',
                    ),
                ),
            ],
        ),
        migrations.RunPython(create_quay_template_implicit_roles, noop_reverse),
    ]
