# Generated by Codex on 2026-07-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0262_quay_image_build_template_unified_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitystream',
            name='quay_image_build_template',
            field=models.ManyToManyField(blank=True, to='main.quayimagebuildtemplate'),
        ),
        migrations.AddField(
            model_name='activitystream',
            name='quay_image_build_job',
            field=models.ManyToManyField(blank=True, to='main.quayimagebuildjob'),
        ),
    ]
