# Generated by Codex on 2026-07-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0263_activity_stream_quay_image_build_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectupdate',
            name='eda_sync',
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text='Whether this project update should reconcile the project with Event Engine after a successful source update.',
            ),
        ),
    ]
