# Generated by Codex on 2026-07-30

import uuid

import awx.main.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0264_projectupdate_eda_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='terraformjobtemplate',
            name='state_backend',
            field=models.CharField(
                choices=[('terraform', 'Terraform configuration'), ('git', 'Capstan managed Git')],
                default='terraform',
                help_text='Use the backend declared by the Terraform configuration, or let Capstan persist encrypted local state in a Git project.',
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name='terraformjobtemplate',
            name='state_branch',
            field=models.CharField(
                blank=True,
                default='capstan-terraform-state',
                help_text='Dedicated Git branch used for encrypted Terraform state revisions.',
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name='terraformjobtemplate',
            name='state_encryption_key',
            field=models.CharField(
                blank=True,
                default='',
                editable=False,
                help_text='Encrypted data-encryption key for managed Terraform state.',
                max_length=2048,
            ),
        ),
        migrations.AddField(
            model_name='terraformjobtemplate',
            name='state_key',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Stable logical key for this state. When empty, Capstan uses "template-<id>". The key may contain letters, numbers, ".", "_", "-", and "/".',
                max_length=1024,
            ),
        ),
        migrations.AddField(
            model_name='terraformjobtemplate',
            name='state_project',
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text='Git project used to persist encrypted Terraform state. When empty, the Terraform source project is used.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='terraform_state_templates',
                to='main.project',
            ),
        ),
        migrations.AddField(
            model_name='terraformjob',
            name='state_backend',
            field=models.CharField(
                choices=[('terraform', 'Terraform configuration'), ('git', 'Capstan managed Git')],
                default='terraform',
                help_text='State management mode used for this job.',
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name='terraformjob',
            name='state_branch',
            field=models.CharField(
                blank=True,
                default='capstan-terraform-state',
                help_text='Git branch used to persist encrypted state for this job.',
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name='terraformjob',
            name='state_key',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Logical managed state key used for this job.',
                max_length=1024,
            ),
        ),
        migrations.AddField(
            model_name='terraformjob',
            name='state_project',
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text='Git project used to persist encrypted state for this job.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='terraform_state_jobs',
                to='main.project',
            ),
        ),
        migrations.CreateModel(
            name='TerraformStateRevision',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created', models.DateTimeField(default=None, editable=False)),
                ('modified', models.DateTimeField(default=None, editable=False)),
                ('state_key', models.CharField(max_length=1024)),
                ('state_branch', models.CharField(max_length=255)),
                ('state_path', models.CharField(max_length=1024)),
                ('git_commit', models.CharField(blank=True, default='', max_length=64)),
                ('checksum', models.CharField(max_length=64)),
                ('serial', models.BigIntegerField(blank=True, default=None, null=True)),
                ('lineage', models.CharField(blank=True, default='', max_length=255)),
                ('terraform_version', models.CharField(blank=True, default='', max_length=64)),
                ('resource_count', models.PositiveIntegerField(default=0)),
                ('output_count', models.PositiveIntegerField(default=0)),
                (
                    'operation',
                    models.CharField(
                        choices=[('apply', 'Apply'), ('plan', 'Plan'), ('destroy', 'Destroy')],
                        default='apply',
                        max_length=16,
                    ),
                ),
                ('job_status', models.CharField(blank=True, default='', max_length=32)),
                ('summary', awx.main.fields.JSONBlob(blank=True, default=dict)),
                (
                    'state_project',
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='terraform_state_revisions',
                        to='main.project',
                    ),
                ),
                (
                    'terraform_job',
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='state_revisions',
                        to='main.terraformjob',
                    ),
                ),
                (
                    'terraform_job_template',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='state_revisions',
                        to='main.terraformjobtemplate',
                    ),
                ),
            ],
            options={
                'ordering': ('-created', '-id'),
            },
        ),
        migrations.AddField(
            model_name='terraformjob',
            name='state_revision_read',
            field=models.ForeignKey(
                blank=True,
                default=None,
                editable=False,
                help_text='Managed state revision restored before this job ran.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='jobs_restored',
                to='main.terraformstaterevision',
            ),
        ),
        migrations.AddField(
            model_name='terraformjob',
            name='state_revision_written',
            field=models.ForeignKey(
                blank=True,
                default=None,
                editable=False,
                help_text='Managed state revision published by this job.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='jobs_published',
                to='main.terraformstaterevision',
            ),
        ),
        migrations.CreateModel(
            name='TerraformStateLock',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created', models.DateTimeField(default=None, editable=False)),
                ('modified', models.DateTimeField(default=None, editable=False)),
                ('scope', models.CharField(max_length=64, unique=True)),
                ('lock_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('state_branch', models.CharField(max_length=255)),
                (
                    'state_project',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='terraform_state_locks',
                        to='main.project',
                    ),
                ),
                (
                    'terraform_job',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='state_locks',
                        to='main.terraformjob',
                    ),
                ),
                (
                    'terraform_job_template',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='state_locks',
                        to='main.terraformjobtemplate',
                    ),
                ),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.AddIndex(
            model_name='terraformstaterevision',
            index=models.Index(
                fields=['terraform_job_template', 'state_key', '-created'],
                name='main_tfstat_templat_766e4f_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='terraformstaterevision',
            index=models.Index(fields=['git_commit'], name='main_tfstat_git_com_48660d_idx'),
        ),
    ]
