# Generated by Codex on 2026-07-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0265_terraform_managed_git_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_saas_tenant',
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text='Designates an organization created through the Capstan SaaS tenant registration flow.',
            ),
        ),
        migrations.AddField(
            model_name='organization',
            name='tenant_slug',
            field=models.SlugField(
                blank=True,
                editable=False,
                help_text='Stable public identifier for a SaaS tenant.',
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name='organization',
            name='tenant_status',
            field=models.CharField(
                blank=True,
                choices=[('active', 'Active'), ('suspended', 'Suspended'), ('deleting', 'Deleting')],
                default='',
                editable=False,
                help_text='Lifecycle status for a SaaS tenant. Self-hosted organizations leave this blank.',
                max_length=16,
            ),
        ),
    ]
