# Generated by Django 5.2.8 on 2026-07-31 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0266_organization_saas_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='tenant_organization',
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text='SaaS tenant that exclusively owns this execution instance.',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='execution_instances',
                to='main.organization',
            ),
        ),
        migrations.AddField(
            model_name='instancegroup',
            name='tenant_organization',
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text='SaaS tenant that exclusively owns this execution pool.',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='execution_pools',
                to='main.organization',
            ),
        ),
        migrations.AddField(
            model_name='instancegroup',
            name='tenant_status',
            field=models.CharField(
                blank=True,
                choices=[('active', 'Active'), ('suspended', 'Suspended'), ('retired', 'Retired')],
                default='',
                help_text='Lifecycle state for a tenant-owned execution pool.',
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name='instance',
            constraint=models.CheckConstraint(
                condition=models.Q(('tenant_organization__isnull', True), ('node_type', 'execution'), _connector='OR'),
                name='tenant_instance_must_be_execution_node',
                violation_error_message='Tenant-owned instances must be execution nodes.',
            ),
        ),
        migrations.AddConstraint(
            model_name='instancegroup',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(('tenant_organization__isnull', True), ('tenant_status', '')),
                    models.Q(('tenant_organization__isnull', False), ('tenant_status__in', ['active', 'suspended', 'retired'])),
                    _connector='OR',
                ),
                name='tenant_execution_pool_requires_lifecycle_state',
                violation_error_message='Tenant execution pools require a lifecycle state; shared groups must not define one.',
            ),
        ),
    ]
