# Generated by Django 5.2.8 on 2026-07-31

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0267_instance_tenant_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='tenant_terms_accepted_at',
            field=models.DateTimeField(
                blank=True,
                default=None,
                editable=False,
                help_text='Time at which the initial SaaS tenant administrator accepted the legal terms.',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='organization',
            name='tenant_terms_accepted_by_email',
            field=models.EmailField(
                blank=True,
                default='',
                editable=False,
                help_text='Verified email address that accepted the SaaS tenant legal terms.',
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name='organization',
            name='tenant_terms_version',
            field=models.CharField(
                blank=True,
                default='',
                editable=False,
                help_text='Legal terms version accepted when this SaaS tenant was provisioned.',
                max_length=64,
            ),
        ),
        migrations.CreateModel(
            name='SaaSTenantRegistration',
            fields=[
                ('created', models.DateTimeField(default=None, editable=False)),
                ('modified', models.DateTimeField(default=None, editable=False)),
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=512)),
                ('organization_slug', models.SlugField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=150)),
                ('last_name', models.CharField(blank=True, default='', max_length=150)),
                ('password_hash', models.CharField(max_length=128)),
                ('verification_nonce', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('terms_version', models.CharField(max_length=64)),
                ('terms_accepted_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('verified_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
