---
- name: Deploy AWX to Kubernetes
  hosts: all
  gather_facts: false
  vars:
    awx_deploy_method: k8s
  roles:
    - awx_k8s
    - role: awx_gatekeeper_k8s
      when: awx_gatekeeper_enabled | default(false) | bool
    - role: awx_eda_k8s
      when: awx_eda_enabled | default(false) | bool
    - role: awx_galaxy_ng_k8s
      when: awx_galaxy_ng_enabled | default(false) | bool
