---
- name: Install k3s
  hosts: awx_k3s_servers
  gather_facts: true
  become: true
  roles:
    - awx_k3s

- name: Deploy AWX to k3s
  hosts: awx_k3s_servers[0]
  gather_facts: true
  become: true
  vars:
    awx_k8s_kubectl_binary: /usr/local/bin/kubectl
  roles:
    - awx_k8s

- name: Deploy EDA to k3s
  hosts: awx_k3s_servers[0]
  gather_facts: true
  become: true
  vars:
    awx_k8s_kubectl_binary: /usr/local/bin/kubectl
  roles:
    - role: awx_eda_k8s
      when: awx_eda_enabled | bool
