---
- name: Install HAProxy
  ansible.builtin.package:
    name: haproxy
    state: present

- name: Render HAProxy config
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: "0644"
  notify: Restart HAProxy

- name: Enable HAProxy
  ansible.builtin.service:
    name: haproxy
    enabled: true
    state: started
