---
galaxy_info:
  role_name: awx_k8s_failback
  author: Capstan
  description: Fail back Capstan in a k3s or Kubernetes deployment.
  license: Apache-2.0
  min_ansible_version: "2.15"
dependencies:
  - role: awx_deploy_common
