---
awx_deploy_method: k8s
awx_k8s_kubectl_binary: kubectl
awx_k8s_kubeconfig: "{{ lookup('env', 'KUBECONFIG') }}"
awx_gatekeeper_enabled: false
awx_gatekeeper_namespace: gatekeeper-system
awx_gatekeeper_version: v3.22.2
awx_gatekeeper_manifest_url: "https://raw.githubusercontent.com/open-policy-agent/gatekeeper/{{ awx_gatekeeper_version }}/deploy/gatekeeper.yaml"
awx_gatekeeper_wait_for_rollout: true
awx_gatekeeper_controller_deployment: gatekeeper-controller-manager
awx_gatekeeper_audit_deployment: gatekeeper-audit
